// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oranges_ASPNet.Data.Context;

#nullable disable

namespace Oranges_ASPNet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220517111038_AddSeedDataPeakDesignkkk")]
    partial class AddSeedDataPeakDesignkkk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Oranges_ASPNet.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Brand")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = 1,
                            Category = 2,
                            Description = "An iconic, award-winning pack for everyday and photo carry, the newly revamped Everyday Backpack is built around access, organization, expansion, and protection. Unique MagLatch hardware provides lightning fast top access, with dual side access via two weatherproof UltraZips.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/2986/1172/products/black-edb20_1024x1024.jpg?v=1595964079",
                            Model = "Everyday Backpack",
                            Price = 279.95m
                        },
                        new
                        {
                            Id = 2,
                            Brand = 1,
                            Category = 1,
                            Description = "The all-new Everyday Messenger is the latest rev of our original award-winning everyday and photo carry workhorse—the bag that we designed with renowned photographer Trey Ratcliff and honed with the feedback of thousands of customers.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/2986/1172/products/black-EDMbl01_1024x1024.jpg?v=1574661040",
                            Model = "Everyday Messenger",
                            Price = 229.95m
                        },
                        new
                        {
                            Id = 3,
                            Brand = 1,
                            Category = 3,
                            Description = "The 65L Duffel is a monster gear-hauler, ruggedly dependable for airline check-in and road trips. Both bags feature removable padded top handles, a removable padded shoulder strap, 2 internal mesh pockets, and 4 external side pockets for added organization.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/2986/1172/products/1-PDP-Lightbox-Duffel65-BLACK-01-edit_1024x1024.jpg?v=1644352278",
                            Model = "Travel Duffel",
                            Price = 169.95m
                        },
                        new
                        {
                            Id = 4,
                            Brand = 1,
                            Category = 2,
                            Description = "The smaller sibling of our iconic 45L Travel Backpack, the 30L is a rugged, expandable daypack ideal for shorter travel and everyday carry. A big, beautiful rear hatch provides total access for easy packing and unpacking.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/2986/1172/products/1-LIGHTBOX-1024x1024-TRBP-BLACK-02_6db62b4c-ff89-4612-9c69-e033a00897c5_1024x1024.jpg?v=1643233483",
                            Model = "Travel Backpack 30L",
                            Price = 229.95m
                        },
                        new
                        {
                            Id = 5,
                            Brand = 7,
                            Category = 1,
                            Description = "This sleek and modern messenger bag is perfect for your daily journeys. It features premium craftsmanship, world-class organizational compartments and weatherproof construction that's ready to take on anything.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/0058/6514/4418/products/alpha-hero_1020x1200.jpg?v=1636031359",
                            Model = "Alpha Messenger",
                            Price = 144.95m
                        },
                        new
                        {
                            Id = 6,
                            Brand = 7,
                            Category = 2,
                            Description = "The Elements Backpack is designed with organization in mind: pockets for laptop and tablet space, deep zips to hide things away - the perfect choice whether you're commuting or just grabbing coffee.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/0058/6514/4418/products/elements-backpack-hero2_1020x1200.jpg?v=1633353165",
                            Model = "Elements Backpack",
                            Price = 229.95m
                        },
                        new
                        {
                            Id = 7,
                            Brand = 7,
                            Category = 2,
                            Description = "The smaller sibling of our iconic 45L Travel Backpack, the 30L is a rugged, expandable daypack ideal for shorter travel and everyday carry. A big, beautiful rear hatch provides total access for easy packing and unpacking.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/2986/1172/products/1-LIGHTBOX-1024x1024-TRBP-BLACK-02_6db62b4c-ff89-4612-9c69-e033a00897c5_1024x1024.jpg?v=1643233483",
                            Model = "Travel Backpack 30L",
                            Price = 154.95m
                        },
                        new
                        {
                            Id = 8,
                            Brand = 7,
                            Category = 4,
                            Description = "Make the most of every day with Bravo Sling Max (Pro), a slashproof messenger-style sling bag that you can take anywhere. It comes equipped with an adjustable shoulder strap for maximum comfort/minimal stress and a self-locking magnetic buckle - for extra peace of mind.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/0058/6514/4418/products/BravoMaxPro_0000_HeroDark_1020x1200.jpg?v=1639401857",
                            Model = "Bravo Sling Max (PRO)",
                            Price = 135.95m
                        },
                        new
                        {
                            Id = 9,
                            Brand = 3,
                            Category = 5,
                            Description = "LEVEL8’s Pro Carry-on with Laptop Pocket is another one of our Red Dot award winning luggage. Finely crafted with aerospace-grade Bayer Makrolon. We’ve designed this luggage to be water-resistant, lightweight, and have a durable hard-shell casing to protect your most expensive items. We’ve combined the sense of confidence, intelligence, and sophistication to complement its excellence in functionality. Enhanced with ultra-quite 360° spinner wheels that can handle the cobblestone streets of Europe and ensure a delightful walk to your airport gate number.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/0029/3404/6831/products/2_1800x1800.jpg?v=1644919395",
                            Model = "Pro Carry-On With Laptop Pocket 20",
                            Price = 209.95m
                        },
                        new
                        {
                            Id = 10,
                            Brand = 3,
                            Category = 5,
                            Description = "One of our best-selling and Red Dot award winning luggage. LEVEL8 Gibraltar Aluminum luggage is finely crafted with Aerospace-grade aluminum magnesium alloy. We’ve made sure our products are designed to promote the sense of intelligence, confidence, and maturity along with excellence in functionality.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/0029/3404/6831/products/aluminumsilver_fd88d170-88cc-4ba1-a35c-ac8f4a47c47b_1800x1800.jpg?v=1606816036",
                            Model = "Full Aluminium Carry-On 20",
                            Price = 399.95m
                        },
                        new
                        {
                            Id = 11,
                            Brand = 5,
                            Category = 2,
                            Description = "One of our best-selling and Red Dot award winning luggage. LEVEL8 Gibraltar Aluminum luggage is finely crafted with Aerospace-grade aluminum magnesium alloy. We’ve made sure our products are designed to promote the sense of intelligence, confidence, and maturity along with excellence in functionality.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/0051/0368/1570/products/web_prvke_blue_2000x_e9a3b0dc-f040-47e9-8896-232dd98a50de_2000x.jpg?v=1569290940",
                            Model = "Original Prvke",
                            Price = 194.32m
                        });
                });

            modelBuilder.Entity("Oranges_ASPNet.Models.ProductStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("ProductStocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 3,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 4,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 5,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 6,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 7,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 8,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 9,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 10,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 11,
                            Quantity = 5
                        });
                });

            modelBuilder.Entity("Oranges_ASPNet.Models.ProductStock", b =>
                {
                    b.HasOne("Oranges_ASPNet.Models.Product", "Product")
                        .WithOne("Stock")
                        .HasForeignKey("Oranges_ASPNet.Models.ProductStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Oranges_ASPNet.Models.Product", b =>
                {
                    b.Navigation("Stock")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
