// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oranges_ASPNet.Data.Context;

#nullable disable

namespace Oranges_ASPNet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Oranges_ASPNet.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Oranges_ASPNet.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "San Francisco, 2325 3rd St",
                            Country = "USA",
                            LogoUrl = "https://cdn.shopify.com/s/files/1/2986/1172/t/6/assets/headerlogo-10.svg?v=176056868021860541011535753837",
                            Name = "Peak Design"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Pohjoisesplanadi 31",
                            Country = "Finland",
                            LogoUrl = "https://www.rimowa.com/on/demandware.static/-/Library-Sites-RimowaSharedLibrary/default/dwc27c7ee1/images/rim-logo-footer.svg",
                            Name = "Rimowa"
                        },
                        new
                        {
                            Id = 3,
                            Address = "New York 1234",
                            Country = "USA",
                            LogoUrl = "https://cdn.shopify.com/s/files/1/0029/3404/6831/files/6557dada9ef6da560b32c369936db50d_160x@2x.png?v=1538020561",
                            Name = "Level 8"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Beaverton",
                            Country = "New Zealand",
                            LogoUrl = "https://cdn.shopify.com/s/files/1/0281/4984/files/minaal-wordmark-logo_140x@2x.png?v=1642373413",
                            Name = "Minaal"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Clinton Street",
                            Country = "USA",
                            LogoUrl = "https://cdn.shopify.com/s/files/1/0051/0368/1570/files/WANDRD_Logo_410x.png?v=1552584995",
                            Name = "Wandrd"
                        },
                        new
                        {
                            Id = 6,
                            Address = "George Town 1",
                            Country = "USA",
                            LogoUrl = "https://cdn.shopify.com/s/files/1/0104/4630/7364/files/Boundary_Supply_Logo_320x.png?v=1641925041",
                            Name = "Boundary Supply"
                        },
                        new
                        {
                            Id = 7,
                            Address = "425 Smith Street",
                            Country = "USA",
                            LogoUrl = "https://storage.googleapis.com/tapcart-150607.appspot.com/12ac4f59f653659f45fac29fbeff088b_AppIconjpg.jpeg",
                            Name = "Alpaka"
                        });
                });

            modelBuilder.Entity("Oranges_ASPNet.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Oranges_ASPNet.Models.OrderDetails", b =>
                {
                    b.Property<int>("OrderDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailsId"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal (18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailsId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Oranges_ASPNet.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductCampaignId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ProductCampaignId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Category = 2,
                            Description = "An iconic, award-winning pack for everyday and photo carry, the newly revamped Everyday Backpack is built around access, organization, expansion, and protection. Unique MagLatch hardware provides lightning fast top access, with dual side access via two weatherproof UltraZips.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/2986/1172/products/black-edb20_1024x1024.jpg?v=1595964079",
                            Model = "Everyday Backpack",
                            Price = 279.95m
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            Category = 1,
                            Description = "The all-new Everyday Messenger is the latest rev of our original award-winning everyday and photo carry workhorse—the bag that we designed with renowned photographer Trey Ratcliff and honed with the feedback of thousands of customers.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/2986/1172/products/black-EDMbl01_1024x1024.jpg?v=1574661040",
                            Model = "Everyday Messenger",
                            Price = 229.95m
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            Category = 3,
                            Description = "The 65L Duffel is a monster gear-hauler, ruggedly dependable for airline check-in and road trips. Both bags feature removable padded top handles, a removable padded shoulder strap, 2 internal mesh pockets, and 4 external side pockets for added organization.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/2986/1172/products/1-PDP-Lightbox-Duffel65-BLACK-01-edit_1024x1024.jpg?v=1644352278",
                            Model = "Travel Duffel",
                            Price = 169.95m
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 1,
                            Category = 2,
                            Description = "The smaller sibling of our iconic 45L Travel Backpack, the 30L is a rugged, expandable daypack ideal for shorter travel and everyday carry. A big, beautiful rear hatch provides total access for easy packing and unpacking.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/2986/1172/products/1-LIGHTBOX-1024x1024-TRBP-BLACK-02_6db62b4c-ff89-4612-9c69-e033a00897c5_1024x1024.jpg?v=1643233483",
                            Model = "Travel Backpack 30L",
                            Price = 229.95m
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 7,
                            Category = 1,
                            Description = "This sleek and modern messenger bag is perfect for your daily journeys. It features premium craftsmanship, world-class organizational compartments and weatherproof construction that's ready to take on anything.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/0058/6514/4418/products/alpha-hero_1020x1200.jpg?v=1636031359",
                            Model = "Alpha Messenger",
                            Price = 144.95m
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 7,
                            Category = 2,
                            Description = "The Elements Backpack is designed with organization in mind: pockets for laptop and tablet space, deep zips to hide things away - the perfect choice whether you're commuting or just grabbing coffee.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/0058/6514/4418/products/elements-backpack-hero2_1020x1200.jpg?v=1633353165",
                            Model = "Elements Backpack",
                            Price = 229.95m
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 7,
                            Category = 2,
                            Description = "An accordion-style organizational opening that provides greater space to store all of your tech essentials neatly.\r\n\r\nSoft-touch, fleece-lined laptop + tablet compartments that provide all-around protection for your devices and quick-access pockets make organization easy. Detachable shoulder strap for multiple carrying options.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/0058/6514/4418/products/TechBrief_0027_14BALL_1000x.jpg?v=1638947444",
                            Model = "Elements tech brief",
                            Price = 119m
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 7,
                            Category = 4,
                            Description = "Make the most of every day with Bravo Sling Max (Pro), a slashproof messenger-style sling bag that you can take anywhere. It comes equipped with an adjustable shoulder strap for maximum comfort/minimal stress and a self-locking magnetic buckle - for extra peace of mind.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/0058/6514/4418/products/BravoMaxPro_0000_HeroDark_1020x1200.jpg?v=1639401857",
                            Model = "Bravo Sling Max (PRO)",
                            Price = 135.95m
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 3,
                            Category = 5,
                            Description = "LEVEL8’s Pro Carry-on with Laptop Pocket is another one of our Red Dot award winning luggage. Finely crafted with aerospace-grade Bayer Makrolon. We’ve designed this luggage to be water-resistant, lightweight, and have a durable hard-shell casing to protect your most expensive items. We’ve combined the sense of confidence, intelligence, and sophistication to complement its excellence in functionality. Enhanced with ultra-quite 360° spinner wheels that can handle the cobblestone streets of Europe and ensure a delightful walk to your airport gate number.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/0029/3404/6831/products/2_1800x1800.jpg?v=1644919395",
                            Model = "Pro Carry-On With Laptop Pocket 20",
                            Price = 209.95m
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 3,
                            Category = 5,
                            Description = "One of our best-selling and Red Dot award winning luggage. LEVEL8 Gibraltar Aluminum luggage is finely crafted with Aerospace-grade aluminum magnesium alloy. We’ve made sure our products are designed to promote the sense of intelligence, confidence, and maturity along with excellence in functionality.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/0029/3404/6831/products/aluminumsilver_fd88d170-88cc-4ba1-a35c-ac8f4a47c47b_1800x1800.jpg?v=1606816036",
                            Model = "Full Aluminium Carry-On 20",
                            Price = 399.95m
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 3,
                            Category = 5,
                            Description = "Fit more for less. One of our largest check-in luggage we offer. The Voyageur Luggage is finely crafted in design and functionality to offer a larger capacity for longer trips. We’ve heard your complaints, and we’ve listened. We’ve made a wider handle design to make sure that more of your items can fit. Made with the best Bayer Makrolon material to ensure a lightweight and durable scratch-resistant hard-shell. We’ve enhanced the luggage by adding ultra-quite 360° spinner wheels that feel as smooth as silk when walking to your next gate number.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/0029/3404/6831/products/40_1800x1800.jpg?v=1647427682",
                            Model = "Voyageur Check In",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 3,
                            Category = 5,
                            Description = "LEVEL8’s Glitter Carry-on is the latest luggage that comes complete from A to Z with everything you need. This glittering carry-on is expertly crafted with German Makrolon Polycarbonate and further enhanced with ultra-quiet 360° Spinner wheels.  Our goal is to ensure the most deeply satisfying luggage for your adventures by creating an elegantly fashionable, robust, secure, and lightweight piece of luggage that represents your exquisite approach to travel in style.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/0029/3404/6831/products/4-2_1800x1800.jpg?v=1652844159",
                            Model = "Glitter Carry On",
                            Price = 269.99m
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 5,
                            Category = 2,
                            Description = "One of our best-selling and Red Dot award winning luggage. LEVEL8 Gibraltar Aluminum luggage is finely crafted with Aerospace-grade aluminum magnesium alloy. We’ve made sure our products are designed to promote the sense of intelligence, confidence, and maturity along with excellence in functionality.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/0051/0368/1570/products/web_prvke_blue_2000x_e9a3b0dc-f040-47e9-8896-232dd98a50de_2000x.jpg?v=1569290940",
                            Model = "Original Prvke",
                            Price = 194.32m
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 5,
                            Category = 3,
                            Description = "The HEXAD Access Duffel Backpack is a carry-on sized backpack/duffel hybrid that features a clamshell opening and is the perfect travel bag, whether you're a photographer or not. Built for 3-5 day trips (and even more depending on how light you pack), this bag is weather resistant, durable, and extremely functional. It been featured in and recommended by Carryology, Bless This Stuff, and Digital Trends.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/0051/0368/1570/products/access_green_2000x.png?v=1574986091",
                            Model = "Hexad Access Duffel",
                            Price = 301.69m
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 5,
                            Category = 3,
                            Description = "The HEXAD Carryall Duffel Backpack is more functional than a traditional duffel, and more versatile than a dedicated travel backpack. From day trips to the slopes to weekend travel, this well thought out backpack/duffel hybrid will adapt to whatever adventure you throw at it. It's extremely weather resistant, durable, and versatile.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/0051/0368/1570/products/carryall_open_blue_2000x.png?v=1609344585",
                            Model = "Hexad Carryall Duffel",
                            Price = 265.15m
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 5,
                            Category = 4,
                            Description = "The ROAM 9L Sling is a beautiful and innovative camera-slash-everyday bag built for those that want their cake and want to eat it too. It may look small, but this baby can carry everything you need for a full day of shooting, working, snacking, and all-around butt-kicking. Oh yeah, and it can also fit a 16\" laptop... show us another sling that can do that! We’ll wait. We guarantee that this feature-packed sling is more comfortable than anything else out there. It also features an innovative expandable water bottle/tripod pocket with secure and easy access, removable dividers so you can customize the bag to your needs, and lightning quick access so your gear is always only a moment away. Sling on!",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/0051/0368/1570/products/9LwBlackCase_2000x.png?v=1641941058",
                            Model = "Roam 9L Sling",
                            Price = 186.99m
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 2,
                            Category = 5,
                            Description = "The unmistakable RIMOWA Original aluminum suitcase with its distinctive grooves is regarded as one of the most iconic luggage designs of all time.\r\n\r\nMade from high-end anodized aluminum, the RIMOWA Original Check-In M in silver is engineered with longevity in mind. Remarkably robust and surprisingly lightweight, this medium sized luggage is an unparalleled example of craftsmanship and innovation and provides the traveler with room for longer journeys of up to 5 days.\r\n\r\nDesigned and engineered in Germany.",
                            ImgUrl = "https://www.rimowa.com/on/demandware.static/-/Sites-rimowa-master-catalog-final/default/dw496544eb/images/large/92563004_2.png",
                            Model = "Classic Check-In M",
                            Price = 1360m
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 2,
                            Category = 5,
                            Description = "The first polycarbonate suitcase, designed in Germany to provide the best in high-tech functionality.\r\nStrong, durable, and lightweight, the RIMOWA Essential Check-In L in Bamboo green is the ultimate example of hard shell luggage innovation. Designed to accompany you on a lifetime of journeys, this large check-in suitcase is built to provide room for journeys of up to 10 days.",
                            ImgUrl = "https://www.rimowa.com/on/demandware.static/-/Sites-rimowa-master-catalog-final/default/dw0fe65d56/images/large/83273944_2.png",
                            Model = "Essential Check-In L",
                            Price = 925.99m
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 2,
                            Category = 5,
                            Description = "A thoughtful combination of two of the world’s most advanced materials, the RIMOWA Hybrid Check-In M in all-black unites the resilience of our unique aluminium-magnesium alloy with the supremely lightweight quality of polycarbonate, creating a high-end piece of German engineering designed for a lifetime of purposeful travel.\r\nDesigned and engineered in Germany, this medium-sized suitcase is the ultimate example of luggage innovation and ideal for up to 5 days of travel.",
                            ImgUrl = "https://www.rimowa.com/on/demandware.static/-/Sites-rimowa-master-catalog-final/default/dwcfaa3d95/images/large/88363674_2.png",
                            Model = "Hybrid Check-In M",
                            Price = 1040m
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 2,
                            Category = 5,
                            Description = "Cleverly built for both daily commuting and 1 to 2-day trips, the RIMOWA Original Compact in silver provides travelers with the freedom to determine its use.\r\nSimply remove its interior accordion divider to transform it from a wheeled briefcase to a compact carry-on suitcase that fits in most train and aeroplane luggage compartments. Inside, it is equipped with an interior zipped compartment, multiple pockets to organize essentials, and a large padded compartment that holds a laptop up to 16 inches.",
                            ImgUrl = "https://www.rimowa.com/on/demandware.static/-/Sites-rimowa-master-catalog-final/default/dw8e169aca/images/large/92540004_2.png",
                            Model = "Original Compact",
                            Price = 1135m
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 7,
                            Category = 2,
                            Description = "Boundary's X-Pac material fuses futuristic style with supreme functionality. Errant Pack is an award-winning 22 L modular backpack for everyday use. Technical features and fluid organization enhances your daily rhythm, while the sleek and minimal design seamlessly transitions from the office through the weekend. The core component of an evolving ecosystem of modular accessories, the Errant Pack’s functionality can be customized to your needs, extending the longevity of every product and creating less waste for the planet.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/0104/4630/7364/products/Errant-Pack_X-Pac-Jet-Black_Front_950x.jpg?v=1646766651",
                            Model = "Errant Pack X-Pac",
                            Price = 250m
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 7,
                            Category = 4,
                            Description = "The Errant Sling (formerly known as the Arclite Sling) is built from Stormproof fabrics and zippers to safeguard 15L liters of magnetic compression storage. Constructed to organize and transport your everyday carry essentials; A laptop/tablet compartment is easily accessible through waterproof zippers, so you keep your creative momentum while staying in motion.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/0104/4630/7364/products/TE-ERS-00107-02_950x.jpg?v=1648485482",
                            Model = "Errant Sling",
                            Price = 200m
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 7,
                            Category = 3,
                            Description = "The perfect sidekick for a getaway or trip to the gym, the Errant Duffel (formerly known as the Aegis Duffel) keeps your gear ready and fresh with a ventilated wet/dry compartment. The luggage pass-through, secure quick-access pockets, and carry-on approved size ease your travels, while multiple removable or concealable carry options provide comfort and flexibility. Composed of durable 500D Cordura®, waterproof Hypalon, YKK® StormGuard zippers, and magnetic hardware, this is the ideal duffel for all your on-the-go needs.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/0104/4630/7364/products/Errant-Duffel_Hymassa-Tan_Angle_436ce976-1332-456b-8d93-4a73241a1d00_950x.jpg?v=1638836082",
                            Model = "Errant Duffel",
                            Price = 250m
                        },
                        new
                        {
                            Id = 24,
                            BrandId = 7,
                            Category = 2,
                            Description = "The Prima System's adaptable storage and modular components make life more comfortable by providing a simple carry solution for your personal, photo, and tech gear. The modular backpack has a large 30 L volume, padded laptop sleeve, and an assortment of pockets to organize gear of all sizes. The included camera case and laptop sleeve can be used individually or with the Prima to expand storage and function when you need it most.",
                            ImgUrl = "https://cdn.shopify.com/s/files/1/0104/4630/7364/products/Prima-System_Stone-Grey_System_950x.jpg?v=1634320861",
                            Model = "Prima System",
                            Price = 290m
                        });
                });

            modelBuilder.Entity("Oranges_ASPNet.Models.ProductCampaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ProductCampaign");
                });

            modelBuilder.Entity("Oranges_ASPNet.Models.ProductStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("ProductStocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 3,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 4,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 5,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 6,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 7,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 8,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 9,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 10,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 11,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 12,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 13,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 14,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 15,
                            ProductId = 15,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 16,
                            ProductId = 16,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 17,
                            ProductId = 17,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 18,
                            ProductId = 18,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 19,
                            ProductId = 19,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 20,
                            ProductId = 20,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 21,
                            ProductId = 21,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 22,
                            ProductId = 22,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 23,
                            ProductId = 23,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 24,
                            ProductId = 24,
                            Quantity = 5
                        });
                });

            modelBuilder.Entity("Oranges_ASPNet.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Oranges_ASPNet.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Oranges_ASPNet.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oranges_ASPNet.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Oranges_ASPNet.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Oranges_ASPNet.Models.Order", b =>
                {
                    b.HasOne("Oranges_ASPNet.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Oranges_ASPNet.Models.OrderDetails", b =>
                {
                    b.HasOne("Oranges_ASPNet.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oranges_ASPNet.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Oranges_ASPNet.Models.Product", b =>
                {
                    b.HasOne("Oranges_ASPNet.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oranges_ASPNet.Models.ProductCampaign", "ProductCampaign")
                        .WithMany("Product")
                        .HasForeignKey("ProductCampaignId");

                    b.Navigation("Brand");

                    b.Navigation("ProductCampaign");
                });

            modelBuilder.Entity("Oranges_ASPNet.Models.ProductStock", b =>
                {
                    b.HasOne("Oranges_ASPNet.Models.Product", "Product")
                        .WithOne("Stock")
                        .HasForeignKey("Oranges_ASPNet.Models.ProductStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Oranges_ASPNet.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("Oranges_ASPNet.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Oranges_ASPNet.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Oranges_ASPNet.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Oranges_ASPNet.Models.Product", b =>
                {
                    b.Navigation("Stock")
                        .IsRequired();
                });

            modelBuilder.Entity("Oranges_ASPNet.Models.ProductCampaign", b =>
                {
                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
